# Generated by Django 4.2.2 on 2023-07-05 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='short_description',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=50, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
