# Generated by Django 4.2.2 on 2023-07-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_image', verbose_name='profile image'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_message',
            field=models.CharField(blank=True, max_length=50, verbose_name='status message'),
        ),
    ]
