# Generated by Django 4.2.2 on 2023-07-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delete_at'),
        ),
    ]
