# Generated by Django 4.2.2 on 2023-07-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_friendship_followed_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
